### ISSUE TITLE
After installing Jumio, app crashes when launching third party sdk

### ISSUE THREAD

**Issue by TheTon1k** [Jumio/mobile-react#27]
Tried to run Cardinal Mobile SDK (for Android) after installing Jumio and got a crash (release build only, everything works in debug mode).
It worked without Jumio

**Comment by bratapfelmus** [comment]
Hello @TheTon1k  
any details on the crash?

**Comment by TheTon1k** [comment]
Hi @bratapfelmus 
got this when trying to set up cardinal
`2022-05-19 18:08:40.819 5951-5984/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.testapp, PID: 5951
    java.lang.RuntimeException: Could not invoke CardinalModule.setupCardinalSession
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:22)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:13)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:1)
        at android.os.Looper.loop(Looper.java:236)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:8)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:18)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:13) 
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:1) 
        at android.os.Looper.loop(Looper.java:236) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:8) 
        at java.lang.Thread.run(Thread.java:923) 
     Caused by: java.lang.NoSuchMethodError: No virtual method remove(I)Ljava/lang/Object; in class Lcom/cardinalcommerce/a/o; or its super classes (declaration of 'com.cardinalcommerce.a.o' appears in base.apk)
        at com.cardinalcommerce.a.o.r(:6)
        at com.cardinalcommerce.a.g.a(:13)
        at com.cardinalcommerce.a.g.e(:9)
        at com.cardinalcommerce.a.d.k(:9)
        at o3.a.b(:17)
        at com.testapp.CardinalModule.setupCardinalSession(CardinalModule.java:20)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:18) 
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:13) 
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:1) 
        at android.os.Looper.loop(Looper.java:236) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:8) 
        at java.lang.Thread.run(Thread.java:923) `
        
        I don't understand where the conflict is.

**Comment by bratapfelmus** [comment]
Hello @TheTon1k 
this looks like a crash regarding Cardinal SDK, so I would recommend reaching out to them as well. 
`FATAL EXCEPTION: mqt_native_modules Process: com.testapp, PID: 5951 java.lang.RuntimeException: Could not invoke CardinalModule.setupCardinalSession`

We have not tested running Jumio SDK in an application alongside Cardinal SDK. From what I understand Cardinal also deals with Consumer Authentication. There might be internal dependency conflicts. 

Please contact Jumio support for more details.
