### ISSUE TITLE
[Android] App crash with RN 0.68 -  ARMv7 CPU Architecture with NEON Intrinsics required

### ISSUE THREAD

**Issue by soroush-b** [Jumio/mobile-react#35]
installed brand new project with RN v0.68.1 with Jumio 4.0.0. but app crashes on android with this error

package.json
```
  "dependencies": {
    "react": "17.0.2",
    "react-native": "0.68.1",
    "frisbee": "^3.1.2",
    "react-native-jumio-mobilesdk": "https://github.com/Jumio/mobile-react.git#v4.0.0"
  },
```

```
FATAL EXCEPTION: main
    Process: com.awesomeproject, PID: 22438
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.awesomeproject/com.jumio.defaultui.JumioActivity}: com.jumio.sdk.exceptions.PlatformNotSupportedException: ARMv7 CPU Architecture with NEON Intrinsics required
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: com.jumio.sdk.exceptions.PlatformNotSupportedException: ARMv7 CPU Architecture with NEON Intrinsics required
        at com.jumio.sdk.JumioSDK$Companion.checkSDKRequirements(JumioSDK.kt:154)
        at com.jumio.sdk.JumioSDK.checkSDKRequirements(Unknown Source:2)
        at com.jumio.sdk.JumioSDK.<init>(JumioSDK.kt:159)
        at a.a.a(JumioViewModel.kt:18)
        at a.a.a(JumioViewModel.kt:1)
        at a.a$d.a(JumioViewModel.kt:1)
        at a.a$d.invoke(JumioViewModel.kt:1)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at a.a.p(JumioViewModel.kt:1)
        at a.a.<init>(JumioViewModel.kt:66)
        at a.b.create(JumioViewModelFactory.kt:1)
        at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.java:69)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:185)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:54)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:41)
        at com.jumio.defaultui.JumioActivity.getJumioViewModel(JumioActivity.kt:1)
        at com.jumio.defaultui.JumioActivity.initObservers(JumioActivity.kt:1)
        at com.jumio.defaultui.JumioActivity.onCreate(JumioActivity.kt:17)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
```

**Comment by BernadetteTh** [comment]
Hello @soroush-b 

please be aware that the architectures supported by the Jumio SDK and by extension our RN plugin are:
* ARMv7 processor with Neon
* ARM64-v8a

See also --> https://github.com/Jumio/mobile-sdk-android#general-requirements 
By extension, this means that running on Android emulator is not supported at the moment.

**Comment by soroush-b** [comment]
I see yeah runningis  on real device working fine. thanks for the response.
