### ISSUE TITLE
ARMv7 CPU Architecture with NEON Intrinsics required

### ISSUE THREAD

**Issue by devphilipcesar** [Jumio/mobile-react#50]
**Fatal Exception: java.lang.RuntimeException**
Unable to start activity ComponentInfo{com.purplme.purplapp/com.jumio.defaultui.JumioActivity}: com.jumio.sdk.exceptions.PlatformNotSupportedException: ARMv7 CPU Architecture with NEON Intrinsics required

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.purplme.purplapp/com.jumio.defaultui.JumioActivity}: com.jumio.sdk.exceptions.PlatformNotSupportedException: ARMv7 CPU Architecture with NEON Intrinsics required
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2668)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2729)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1480)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6138)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
```

Caused by com.jumio.sdk.exceptions.PlatformNotSupportedException
ARMv7 CPU Architecture with NEON Intrinsics required

```
Caused by com.jumio.sdk.exceptions.PlatformNotSupportedException: ARMv7 CPU Architecture with NEON Intrinsics required
       at com.jumio.sdk.JumioSDK$Companion.checkSDKRequirements(JumioSDK.kt:11)
       at com.jumio.sdk.JumioSDK.checkSDKRequirements(JumioSDK.kt)
       at com.jumio.sdk.JumioSDK.<init>(JumioSDK.kt:5)
       at jumio.dui.a.a(JumioViewModel.kt:20)
       at jumio.dui.a.a(JumioViewModel.kt:1)
       at jumio.dui.a$e.a(JumioViewModel.kt:1)
       at jumio.dui.a$e.invoke(JumioViewModel.kt:1)
       at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
       at jumio.dui.a.s(JumioViewModel.kt:1)
       at jumio.dui.a.<init>(JumioViewModel.kt:73)
       at jumio.dui.b.create(JumioViewModelFactory.kt:1)
       at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.java:69)
       at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:169)
       at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:139)
       at androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.kt:44)
       at androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.kt:31)
       at com.jumio.defaultui.JumioActivity.getJumioViewModel(JumioActivity.kt:1)
       at com.jumio.defaultui.JumioActivity.initObservers(JumioActivity.kt:1)
       at com.jumio.defaultui.JumioActivity.onCreate(JumioActivity.kt:15)
       at android.app.Activity.performCreate(Activity.java:6785)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1145)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2621)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2729)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1480)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6138)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
```

![image](https://user-images.githubusercontent.com/121386527/223039011-fb12f93b-1258-41a3-8695-ba49e947fe63.png)

**STACK TRACE ERROR CAN BE DOWNLOADED HERE**

[com.purplme.purplapp_issue_0695320f15a3da94269cfad19e649306_crash_session_64031BD2001B00011814B5B8B57A54C1_DNE_0_v2_stacktrace.txt](https://github.com/Jumio/mobile-react/files/10895152/com.purplme.purplapp_issue_0695320f15a3da94269cfad19e649306_crash_session_64031BD2001B00011814B5B8B57A54C1_DNE_0_v2_stacktrace.txt)

**Comment by BernadetteTh** [comment]
Hello @devphilipcesar 
without any information about the architecture you tried to run this on, this looks like the architecture is unsupported. 
This would be the case for the Android emulator, for example. 

Please see our base requirements --> https://github.com/Jumio/mobile-sdk-android#general-requirements

**Comment by devphilipcesar** [comment]
Hi @BernadetteTh ... Thanks for the response... but I doubt this is from Android Emulator as per my screenshot attachment... this happens to one of our customer that is using Android OnePlus A3010 Device under Android 7.1.1 OS Version

For more information this is the device that the user is using 
https://www.gsmarena.com/oneplus_3t-8416.php
